### ISSUE TITLE
Create an UVL parser

### ISSUE THREAD

**Issue by benavidescuevas** [flamapy/uvlparser#2]
We will create an UVL parser for Python. It has to be discussed if the parser will be independent from the reasoning project or not. This is something to be discussed.  This has to be discussed among the @diverso-lab/uvl-team

**Comment by benavidescuevas** [comment]
This can be considered when analysing the tech stack:
Lark and PLY.
There is an option and it is to use ANTLR with Python 3 as target language.  

Here a tutorial to have a look to:  https://medium.com/@raguiar2/building-a-working-calculator-in-python-with-antlr-d879e2ea9058

**Comment by jagalindo** [comment]
We can now close this old- orphan issue
